/*
 * generated by Xtext 2.23.0
 */
package online.yamm.coreModelDsl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractXYammScopeProvider extends XbaseBatchScopeProvider {
}
