/*
 * generated by Xtext 2.25.0
 */
package dev.yamm.util.evalGrammar.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EvalAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("dev/yamm/util/evalGrammar/parser/antlr/internal/InternalEval.tokens");
	}
}
