/*
 * generated by Xtext 2.14.0
 */
package online.yamm.util.evalGrammar.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class EvalProposalProvider extends AbstractEvalProposalProvider {
}
