/*
 * generated by Xtext 2.24.0.M1
 */
package online.yamm.util.evalGrammar.parser.antlr;

import com.google.inject.Inject;
import online.yamm.util.evalGrammar.parser.antlr.internal.InternalEvalParser;
import online.yamm.util.evalGrammar.services.EvalGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class EvalParser extends AbstractAntlrParser {

	@Inject
	private EvalGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEvalParser createParser(XtextTokenStream stream) {
		return new InternalEvalParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}

	public EvalGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EvalGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
