/*
 * generated by Xtext 2.14.0
 */
package dev.yamm.util.evalGrammar


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class EvalStandaloneSetup extends EvalStandaloneSetupGenerated {

	def static void doSetup() {
		new EvalStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
