/*
 * generated by Xtext 2.14.0
 */
package dev.yamm.util.evalGrammar

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class EvalRuntimeModule extends AbstractEvalRuntimeModule {

	def Class<? extends EvalResourceProvider> bindEvalResourceProvider() {
		EvalResourceProvider
	}

}
