/*
 * generated by Xtext 2.25.0
 */
package dev.yamm.util.evalGrammar.ui.tests;

import com.google.inject.Injector;
import dev.yamm.util.evalGrammar.ui.internal.EvalGrammarActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EvalUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return EvalGrammarActivator.getInstance().getInjector("dev.yamm.util.evalGrammar.Eval");
	}

}
