/*
 * generated by Xtext 2.25.0
 */
package dev.yamm.coreModelDsl.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractXYammScopeProvider extends XbaseBatchScopeProvider {
}
