/*
 * generated by Xtext 2.25.0
 */
package dev.yamm.util.evalGrammar.ui;

import com.google.inject.Injector;
import dev.yamm.util.evalGrammar.ui.internal.EvalGrammarActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EvalExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(EvalGrammarActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		EvalGrammarActivator activator = EvalGrammarActivator.getInstance();
		return activator != null ? activator.getInjector(EvalGrammarActivator.DEV_YAMM_UTIL_EVALGRAMMAR_EVAL) : null;
	}

}
