/*
 * generated by Xtext 2.24.0.M1
 */
package online.yamm.util.evalGrammar.ui;

import com.google.inject.Injector;
import online.yamm.util.evalGrammar.ui.internal.EvalGrammarActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EvalExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(EvalGrammarActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		EvalGrammarActivator activator = EvalGrammarActivator.getInstance();
		return activator != null ? activator.getInjector(EvalGrammarActivator.ONLINE_YAMM_UTIL_EVALGRAMMAR_EVAL) : null;
	}

}
