/*
 * generated by Xtext 2.25.0
 */
package dev.yamm.util.evalGrammar.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractEvalScopeProvider extends XbaseBatchScopeProvider {
}
