<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="yammDiagram" nsURI="http://www.yamm.online/coreModelDiagram/YammDiagram"
    nsPrefix="yammDiagram">
  <eClassifiers xsi:type="ecore:EEnum" name="YAggregationKind">
    <eLiterals name="none" literal="none"/>
    <eLiterals name="shared" value="1" literal="shared"/>
    <eLiterals name="composite" value="2" literal="composite"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YClass" eSuperTypes="#//YElement #//YNamedElement #//YPackageableElement #//YClassifier #//YType #//YNamespace #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//YNamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superClass" unique="false"
        upperBound="-1" eType="#//YClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAttribute" upperBound="-1"
        eType="#//YProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperation" upperBound="-1"
        eType="#//YOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observeQueue" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YClassifier" eSuperTypes="#//YObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="YComment" eSuperTypes="#//YElement #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotatedElement" unique="false"
        upperBound="-1" eType="#//YElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" eType="#//YComment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//YElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YConstraint" eSuperTypes="#//YElement #//YNamedElement #//YPackageableElement #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedElement" unique="false"
        upperBound="-1" eType="#//YElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" eType="#//YComment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//YElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="specification" eType="#//YOperation"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YDataType" eSuperTypes="#//YObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="YElement" eSuperTypes="#//YObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="YElementImport" eSuperTypes="#//YElement #//YObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedElement" eType="#//YPackageableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importingNamespace" eType="#//YNamespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" eType="#//YComment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//YElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YEnumeration" eSuperTypes="#//YElement #//YNamedElement #//YPackageableElement #//YClassifier #//YType #//YNamespace #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" unique="false"
        upperBound="-1" eType="#//YNamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementImport" unique="false"
        upperBound="-1" eType="#//YPackageableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedMember" unique="false"
        upperBound="-1" eType="#//YPackageableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageImport" unique="false"
        upperBound="-1" eType="#//YPackageableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" unique="false"
        upperBound="-1" eType="#//YProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" unique="false"
        upperBound="-1" eType="#//YFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" unique="false"
        upperBound="-1" eType="#//YClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedMember" unique="false"
        upperBound="-1" eType="#//YNamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//YNamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" eType="#//YComment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//YElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMember" upperBound="-1"
        eType="#//YNamedElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRule" upperBound="-1"
        eType="#//YConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLiteral" upperBound="-1"
        eType="#//YEnumerationLiteral" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YEnumerationLiteral" eSuperTypes="#//YElement #//YNamedElement #//YPackageableElement #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" eType="#//YComment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//YElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YFeature" eSuperTypes="#//YObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="YNamedElement" eSuperTypes="#//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YNamespace" eSuperTypes="#//YObject"/>
  <eClassifiers xsi:type="ecore:EClass" name="YOperation" eSuperTypes="#//YElement #//YNamedElement #//YFeature #//YNamespace #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameter" upperBound="-1"
        eType="#//YParameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" eType="#//YStateMachine"
        containment="true" eOpposite="#//YStateMachine/operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clazz" eType="#//YClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="returnType" eType="#//YType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YPackage" eSuperTypes="#//YElement #//YNamedElement #//YPackageableElement #//YNamespace #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//YPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMemberPackage" upperBound="-1"
        eType="#//YPackageableElement" containment="true" eOpposite="#//YPackageableElement/parentElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YPackageableElement" eSuperTypes="#//YObject #//YNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentElement" eType="#//YPackage"
        eOpposite="#//YPackage/ownedMemberPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YPackageImport" eSuperTypes="#//YElement #//YObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedPackage" eType="#//YPackage"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importingNamespace" eType="#//YNamespace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" eType="#//YComment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//YElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YParameter" eSuperTypes="#//YElement #//YNamedElement #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//YParameterDirectionKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//YType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperboundWildcard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YParameterDirectionKind">
    <eLiterals name="in" literal="in"/>
    <eLiterals name="inout" value="1" literal="inout"/>
    <eLiterals name="inDeep" value="2" literal="inDeep"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YPrimitiveType" eSuperTypes="#//YElement #//YNamedElement #//YPackageableElement #//YClassifier #//YType #//YNamespace #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="member" unique="false"
        upperBound="-1" eType="#//YNamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elementImport" unique="false"
        upperBound="-1" eType="#//YPackageableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="importedMember" unique="false"
        upperBound="-1" eType="#//YPackageableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packageImport" unique="false"
        upperBound="-1" eType="#//YPackageableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" unique="false"
        upperBound="-1" eType="#//YProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" unique="false"
        upperBound="-1" eType="#//YFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="general" unique="false"
        upperBound="-1" eType="#//YClassifier"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritedMember" unique="false"
        upperBound="-1" eType="#//YNamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//YNamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" eType="#//YComment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//YElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMember" upperBound="-1"
        eType="#//YNamedElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRule" upperBound="-1"
        eType="#//YConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YProperty" eSuperTypes="#//YElement #//YNamedElement #//YFeature #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOrdered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerivedUnion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="association" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upper" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" eType="#//YAggregationKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="featuringClassifier" unique="false"
        upperBound="-1" eType="#//YClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//YType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subsettedProperty" unique="false"
        upperBound="-1" eType="#//YProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="opposite" eType="#//YProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" eType="#//YComment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//YElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clazz" eType="#//YClass"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="signature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="#//YVisibilityKind"
        defaultValueLiteral="public"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observe" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invariant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="static" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YType" eSuperTypes="#//YObject #//YNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="YStateMachine" eSuperTypes="#//YElement #//YNamedElement #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="desInitializer" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rtc" eType="#//YRunToCompletion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxEffectsToBeProcessed"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledOperation" eType="#//YOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" eType="#//YComment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//YElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" upperBound="-1"
        eType="#//YTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subvertex" upperBound="-1"
        eType="#//YVertex" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trAttach" upperBound="-1"
        eType="#//YTrAttachment" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operation" lowerBound="1"
        eType="#//YOperation" eOpposite="#//YOperation/stateMachine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YRunToCompletion">
    <eLiterals name="effect" literal="effect"/>
    <eLiterals name="transition" value="1" literal="transition"/>
    <eLiterals name="statemachine" value="2" literal="statemachine"/>
    <eLiterals name="observer" value="3" literal="observer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YTransition" eSuperTypes="#//YElement #//YNamedElement #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//YVertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//YVertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachment" eType="#//YTrAttachment"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComment" eType="#//YComment"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElement" upperBound="-1"
        eType="#//YElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YTrAttachment" eSuperTypes="#//YElement #//YNamedElement #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" eType="#//YTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effects" upperBound="-1"
        eType="#//YEffect" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="guardStringRep" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YEffect" eSuperTypes="#//YObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="body" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="breakpoint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectStringRep" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YVertex" eSuperTypes="#//YObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" unique="false"
        upperBound="-1" eType="#//YTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" unique="false"
        upperBound="-1" eType="#//YTransition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YPseudostate" eSuperTypes="#//YElement #//YNamedElement #//YVertex #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YFinalState" eSuperTypes="#//YElement #//YNamedElement #//YVertex #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YState" eSuperTypes="#//YElement #//YNamedElement #//YNamespace #//YVertex #//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YModel" eSuperTypes="#//YObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clazz" upperBound="-1"
        eType="#//YClass" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="enumerations" upperBound="-1"
        eType="#//YEnumeration" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//YPackage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="objects" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedEdges" upperBound="-1"
        eType="#//YSharedEdge" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="compositeEdges" upperBound="-1"
        eType="#//YCompositeEdge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YSharedEdge" eSuperTypes="#//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//YClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//YClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YCompositeEdge" eSuperTypes="#//YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" eType="#//YClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//YClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ObjectID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="e" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dslInfo" eType="#//DslInfo"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YStateMachineHandler" eSuperTypes="#//YObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="state" lowerBound="1" eType="#//YVertex"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" lowerBound="1"
        eType="#//YTransition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSuspended" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectCount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectNo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachine" lowerBound="1"
        eType="#//YStateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effect" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="&quot;&quot;"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="calledFrom" eType="#//YStateMachineHandler"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itsClassID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operationInstance" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effectsProcessed" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxEffectsToBeProcessed"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inAdapters" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectsBindedWithInoutParameters"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameOfRetunVar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objectsToColor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YGlobalStateMachine" eSuperTypes="#//YObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachines" upperBound="-1"
        eType="#//YStateMachine"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateMachineHandlers" upperBound="-1"
        eType="#//YStateMachineHandler"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateMachineHandlerCount"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraintsAllTrue" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hasReturnParam" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramCount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateExitCount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateExitNo" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="o" eType="#//YOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="observerActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EString2" instanceTypeName="EString2"/>
  <eClassifiers xsi:type="ecore:EClass" name="YCreateInstanceExpression" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clazz" eType="#//YClass"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="feature" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmIdentifiableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YPrintExpression" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expression" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YSetReturnValue" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="YVisibilityKind">
    <eLiterals name="public"/>
    <eLiterals name="private" value="1"/>
    <eLiterals name="protected" value="2"/>
    <eLiterals name="package" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YGetInstancesOfExpression" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clazz" eType="#//YClass"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YMemberFeatureCall" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XMemberFeatureCall">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritanceType" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmIdentifiableElement"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitInheritanceType"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YFeatureCall" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XFeatureCall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="explicitInheritanceType"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inheritanceType" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmIdentifiableElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YGetObjectManagement" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YGetLayerInformation" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YColorDFAObject" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="id" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YGetInstances" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YCountFinalStates" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YCountInitialStates" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YCountStates" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YSetAbsoluteNodePropability" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YCountReachableStates" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YCountInValidTransitions" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YSetPopulationSize" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YLoadModel" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="relModelPath" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DslInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="features" upperBound="-1"
        eType="#//EStructuralFeatureToFeatureInfoMap" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstLine" eType="#//Line"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastLine" eType="#//Line"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureInfo"/>
  <eClassifiers xsi:type="ecore:EClass" name="SingleLinePropertyInfo" eSuperTypes="#//FeatureInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="line" eType="#//Line"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GuardInfo" eSuperTypes="#//FeatureInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstLineGuard" eType="#//Line"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastLineGuard" eType="#//Line"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreNotification" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EffectInfo" eSuperTypes="#//FeatureInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstLineEffect" eType="#//Line"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lastLineEffect" eType="#//Line"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ignoreNotification" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainmentInfo" eSuperTypes="#//FeatureInfo">
    <eStructuralFeatures xsi:type="ecore:EReference" name="insertionLine" eType="#//Line"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EStructuralFeatureToFeatureInfoMap"
      instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" eType="ecore:EClass ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EStructuralFeature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//FeatureInfo"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pos" ordered="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="processedOffsets" ordered="false"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YStructure"/>
  <eClassifiers xsi:type="ecore:EClass" name="YObserverAddValue" eSuperTypes="../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
