/*
 * generated by Xtext 2.14.0
 */
package dev.yamm.coreModelDsl

import dev.yamm.coreModelDsl.jvmmodel.XYammJvmTypesBuilder
import dev.yamm.coreModelDsl.typesystem.XYammTypeComputer
import org.eclipse.xtext.xbase.jvmmodel.JvmTypesBuilder
import org.eclipse.xtext.xbase.typesystem.computation.ITypeComputer

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class XYammRuntimeModule extends AbstractXYammRuntimeModule {

	def Class<? extends ITypeComputer> bindITypeComputer() {
		XYammTypeComputer
	}

	def Class<? extends JvmTypesBuilder> bindJvmTypesBuilder() {
		XYammJvmTypesBuilder
	}


}
