/*
 * generated by Xtext 2.14.0
 */
package dev.yamm.coreModelDsl

import com.google.inject.Injector
import dev.yamm.coreModelXmi.yamm.YammPackage
import org.eclipse.emf.ecore.EPackage

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class XYammStandaloneSetup extends XYammStandaloneSetupGenerated {

	def static void doSetup() {
		new XYammStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
	
	override void register(Injector injector) {
		if (!EPackage.Registry.INSTANCE.containsKey("http://www.yamm.dev/coreModelXmi/Yamm")) {
			EPackage.Registry.INSTANCE.put("http://www.yamm.dev/coreModelXmi/Yamm", YammPackage.eINSTANCE);
		}
		super.register(injector);
	}
}
