/*
 * generated by Xtext 2.25.0
 */
package dev.yamm.coreModelDsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XYammAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("dev/yamm/coreModelDsl/parser/antlr/internal/InternalXYamm.tokens");
	}
}
