/*
 * generated by Xtext 2.25.0
 */
package dev.yamm.coreModelDsl.parser.antlr;

import com.google.inject.Inject;
import dev.yamm.coreModelDsl.parser.antlr.internal.InternalXYammParser;
import dev.yamm.coreModelDsl.services.XYammGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class XYammParser extends AbstractAntlrParser {

	@Inject
	private XYammGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalXYammParser createParser(XtextTokenStream stream) {
		return new InternalXYammParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "YModel";
	}

	public XYammGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(XYammGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
