/**
 * Copyright (C) 2019 yamm.online, Ralf Buschermöhle
 * 	
 * YAMM is made available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * YAMM makes use of JScience - Java(TM) Tools and Libraries for the 
 * Advancement of Sciences: Copyright (C) 2006 - JScience (http://jscience.org/) 
 * All rights reserved.
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 * 
 * see LICENSE.txt
 * 
 */
/**
 */
package online.yamm.coreModelXmi.yamm.provider;

import java.util.ArrayList;
import java.util.Collection;

import online.yamm.coreModelXmi.yamm.util.YammAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class YammItemProviderAdapterFactory extends YammAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable
{
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public YammItemProviderAdapterFactory()
	{
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YClassItemProvider yClassItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYClassAdapter()
	{
		if (yClassItemProvider == null) {
			yClassItemProvider = new YClassItemProvider(this);
		}

		return yClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YClassifier} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YClassifierItemProvider yClassifierItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YClassifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYClassifierAdapter()
	{
		if (yClassifierItemProvider == null) {
			yClassifierItemProvider = new YClassifierItemProvider(this);
		}

		return yClassifierItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YComment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YCommentItemProvider yCommentItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YComment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYCommentAdapter()
	{
		if (yCommentItemProvider == null) {
			yCommentItemProvider = new YCommentItemProvider(this);
		}

		return yCommentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YConstraint} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YConstraintItemProvider yConstraintItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YConstraint}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYConstraintAdapter()
	{
		if (yConstraintItemProvider == null) {
			yConstraintItemProvider = new YConstraintItemProvider(this);
		}

		return yConstraintItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YDataType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YDataTypeItemProvider yDataTypeItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YDataType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYDataTypeAdapter()
	{
		if (yDataTypeItemProvider == null) {
			yDataTypeItemProvider = new YDataTypeItemProvider(this);
		}

		return yDataTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YElementItemProvider yElementItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYElementAdapter()
	{
		if (yElementItemProvider == null) {
			yElementItemProvider = new YElementItemProvider(this);
		}

		return yElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YElementImport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YElementImportItemProvider yElementImportItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YElementImport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYElementImportAdapter()
	{
		if (yElementImportItemProvider == null) {
			yElementImportItemProvider = new YElementImportItemProvider(this);
		}

		return yElementImportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YEnumeration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YEnumerationItemProvider yEnumerationItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YEnumeration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYEnumerationAdapter()
	{
		if (yEnumerationItemProvider == null) {
			yEnumerationItemProvider = new YEnumerationItemProvider(this);
		}

		return yEnumerationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YEnumerationLiteral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YEnumerationLiteralItemProvider yEnumerationLiteralItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YEnumerationLiteral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYEnumerationLiteralAdapter()
	{
		if (yEnumerationLiteralItemProvider == null) {
			yEnumerationLiteralItemProvider = new YEnumerationLiteralItemProvider(this);
		}

		return yEnumerationLiteralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YFeature} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YFeatureItemProvider yFeatureItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YFeature}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYFeatureAdapter()
	{
		if (yFeatureItemProvider == null) {
			yFeatureItemProvider = new YFeatureItemProvider(this);
		}

		return yFeatureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YNamedElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YNamedElementItemProvider yNamedElementItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YNamedElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYNamedElementAdapter()
	{
		if (yNamedElementItemProvider == null) {
			yNamedElementItemProvider = new YNamedElementItemProvider(this);
		}

		return yNamedElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YNamespace} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YNamespaceItemProvider yNamespaceItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YNamespace}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYNamespaceAdapter()
	{
		if (yNamespaceItemProvider == null) {
			yNamespaceItemProvider = new YNamespaceItemProvider(this);
		}

		return yNamespaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YOperationItemProvider yOperationItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYOperationAdapter()
	{
		if (yOperationItemProvider == null) {
			yOperationItemProvider = new YOperationItemProvider(this);
		}

		return yOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YPackageItemProvider yPackageItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYPackageAdapter()
	{
		if (yPackageItemProvider == null) {
			yPackageItemProvider = new YPackageItemProvider(this);
		}

		return yPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YPackageableElement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YPackageableElementItemProvider yPackageableElementItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YPackageableElement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYPackageableElementAdapter()
	{
		if (yPackageableElementItemProvider == null) {
			yPackageableElementItemProvider = new YPackageableElementItemProvider(this);
		}

		return yPackageableElementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YPackageImport} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YPackageImportItemProvider yPackageImportItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YPackageImport}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYPackageImportAdapter()
	{
		if (yPackageImportItemProvider == null) {
			yPackageImportItemProvider = new YPackageImportItemProvider(this);
		}

		return yPackageImportItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YParameter} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YParameterItemProvider yParameterItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YParameter}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYParameterAdapter()
	{
		if (yParameterItemProvider == null) {
			yParameterItemProvider = new YParameterItemProvider(this);
		}

		return yParameterItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YPrimitiveType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YPrimitiveTypeItemProvider yPrimitiveTypeItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YPrimitiveType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYPrimitiveTypeAdapter()
	{
		if (yPrimitiveTypeItemProvider == null) {
			yPrimitiveTypeItemProvider = new YPrimitiveTypeItemProvider(this);
		}

		return yPrimitiveTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YProperty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YPropertyItemProvider yPropertyItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YProperty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYPropertyAdapter()
	{
		if (yPropertyItemProvider == null) {
			yPropertyItemProvider = new YPropertyItemProvider(this);
		}

		return yPropertyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YTypeItemProvider yTypeItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYTypeAdapter()
	{
		if (yTypeItemProvider == null) {
			yTypeItemProvider = new YTypeItemProvider(this);
		}

		return yTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YStateMachine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YStateMachineItemProvider yStateMachineItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YStateMachine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYStateMachineAdapter()
	{
		if (yStateMachineItemProvider == null) {
			yStateMachineItemProvider = new YStateMachineItemProvider(this);
		}

		return yStateMachineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YTransition} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YTransitionItemProvider yTransitionItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YTransition}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYTransitionAdapter()
	{
		if (yTransitionItemProvider == null) {
			yTransitionItemProvider = new YTransitionItemProvider(this);
		}

		return yTransitionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YTrAttachment} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YTrAttachmentItemProvider yTrAttachmentItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YTrAttachment}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYTrAttachmentAdapter()
	{
		if (yTrAttachmentItemProvider == null) {
			yTrAttachmentItemProvider = new YTrAttachmentItemProvider(this);
		}

		return yTrAttachmentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YEffect} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YEffectItemProvider yEffectItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YEffect}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYEffectAdapter()
	{
		if (yEffectItemProvider == null) {
			yEffectItemProvider = new YEffectItemProvider(this);
		}

		return yEffectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YVertex} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YVertexItemProvider yVertexItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YVertex}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYVertexAdapter()
	{
		if (yVertexItemProvider == null) {
			yVertexItemProvider = new YVertexItemProvider(this);
		}

		return yVertexItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YPseudostate} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YPseudostateItemProvider yPseudostateItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YPseudostate}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYPseudostateAdapter()
	{
		if (yPseudostateItemProvider == null) {
			yPseudostateItemProvider = new YPseudostateItemProvider(this);
		}

		return yPseudostateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YFinalState} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YFinalStateItemProvider yFinalStateItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YFinalState}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYFinalStateAdapter()
	{
		if (yFinalStateItemProvider == null) {
			yFinalStateItemProvider = new YFinalStateItemProvider(this);
		}

		return yFinalStateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YState} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YStateItemProvider yStateItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YState}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYStateAdapter()
	{
		if (yStateItemProvider == null) {
			yStateItemProvider = new YStateItemProvider(this);
		}

		return yStateItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YModelItemProvider yModelItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYModelAdapter()
	{
		if (yModelItemProvider == null) {
			yModelItemProvider = new YModelItemProvider(this);
		}

		return yModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YSharedEdge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YSharedEdgeItemProvider ySharedEdgeItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YSharedEdge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYSharedEdgeAdapter()
	{
		if (ySharedEdgeItemProvider == null) {
			ySharedEdgeItemProvider = new YSharedEdgeItemProvider(this);
		}

		return ySharedEdgeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YCompositeEdge} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YCompositeEdgeItemProvider yCompositeEdgeItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YCompositeEdge}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYCompositeEdgeAdapter()
	{
		if (yCompositeEdgeItemProvider == null) {
			yCompositeEdgeItemProvider = new YCompositeEdgeItemProvider(this);
		}

		return yCompositeEdgeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YObjectItemProvider yObjectItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYObjectAdapter()
	{
		if (yObjectItemProvider == null) {
			yObjectItemProvider = new YObjectItemProvider(this);
		}

		return yObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YStateMachineHandler} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YStateMachineHandlerItemProvider yStateMachineHandlerItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YStateMachineHandler}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYStateMachineHandlerAdapter()
	{
		if (yStateMachineHandlerItemProvider == null) {
			yStateMachineHandlerItemProvider = new YStateMachineHandlerItemProvider(this);
		}

		return yStateMachineHandlerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YGlobalStateMachine} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YGlobalStateMachineItemProvider yGlobalStateMachineItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YGlobalStateMachine}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYGlobalStateMachineAdapter()
	{
		if (yGlobalStateMachineItemProvider == null) {
			yGlobalStateMachineItemProvider = new YGlobalStateMachineItemProvider(this);
		}

		return yGlobalStateMachineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YCreateInstanceExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YCreateInstanceExpressionItemProvider yCreateInstanceExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YCreateInstanceExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYCreateInstanceExpressionAdapter()
	{
		if (yCreateInstanceExpressionItemProvider == null) {
			yCreateInstanceExpressionItemProvider = new YCreateInstanceExpressionItemProvider(this);
		}

		return yCreateInstanceExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YPrintExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YPrintExpressionItemProvider yPrintExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YPrintExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYPrintExpressionAdapter()
	{
		if (yPrintExpressionItemProvider == null) {
			yPrintExpressionItemProvider = new YPrintExpressionItemProvider(this);
		}

		return yPrintExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YSetReturnValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YSetReturnValueItemProvider ySetReturnValueItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YSetReturnValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYSetReturnValueAdapter()
	{
		if (ySetReturnValueItemProvider == null) {
			ySetReturnValueItemProvider = new YSetReturnValueItemProvider(this);
		}

		return ySetReturnValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YGetInstancesOfExpression} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YGetInstancesOfExpressionItemProvider yGetInstancesOfExpressionItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YGetInstancesOfExpression}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYGetInstancesOfExpressionAdapter()
	{
		if (yGetInstancesOfExpressionItemProvider == null) {
			yGetInstancesOfExpressionItemProvider = new YGetInstancesOfExpressionItemProvider(this);
		}

		return yGetInstancesOfExpressionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YMemberFeatureCall} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YMemberFeatureCallItemProvider yMemberFeatureCallItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YMemberFeatureCall}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYMemberFeatureCallAdapter()
	{
		if (yMemberFeatureCallItemProvider == null) {
			yMemberFeatureCallItemProvider = new YMemberFeatureCallItemProvider(this);
		}

		return yMemberFeatureCallItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YFeatureCall} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YFeatureCallItemProvider yFeatureCallItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YFeatureCall}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYFeatureCallAdapter()
	{
		if (yFeatureCallItemProvider == null) {
			yFeatureCallItemProvider = new YFeatureCallItemProvider(this);
		}

		return yFeatureCallItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YGetObjectManagement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YGetObjectManagementItemProvider yGetObjectManagementItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YGetObjectManagement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYGetObjectManagementAdapter()
	{
		if (yGetObjectManagementItemProvider == null) {
			yGetObjectManagementItemProvider = new YGetObjectManagementItemProvider(this);
		}

		return yGetObjectManagementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YGetLayerInformation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YGetLayerInformationItemProvider yGetLayerInformationItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YGetLayerInformation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYGetLayerInformationAdapter()
	{
		if (yGetLayerInformationItemProvider == null) {
			yGetLayerInformationItemProvider = new YGetLayerInformationItemProvider(this);
		}

		return yGetLayerInformationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YColorDFAObject} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YColorDFAObjectItemProvider yColorDFAObjectItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YColorDFAObject}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYColorDFAObjectAdapter()
	{
		if (yColorDFAObjectItemProvider == null) {
			yColorDFAObjectItemProvider = new YColorDFAObjectItemProvider(this);
		}

		return yColorDFAObjectItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YGetInstances} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YGetInstancesItemProvider yGetInstancesItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YGetInstances}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYGetInstancesAdapter()
	{
		if (yGetInstancesItemProvider == null) {
			yGetInstancesItemProvider = new YGetInstancesItemProvider(this);
		}

		return yGetInstancesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YCountFinalStates} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YCountFinalStatesItemProvider yCountFinalStatesItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YCountFinalStates}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYCountFinalStatesAdapter()
	{
		if (yCountFinalStatesItemProvider == null) {
			yCountFinalStatesItemProvider = new YCountFinalStatesItemProvider(this);
		}

		return yCountFinalStatesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YCountInitialStates} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YCountInitialStatesItemProvider yCountInitialStatesItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YCountInitialStates}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYCountInitialStatesAdapter()
	{
		if (yCountInitialStatesItemProvider == null) {
			yCountInitialStatesItemProvider = new YCountInitialStatesItemProvider(this);
		}

		return yCountInitialStatesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YCountStates} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YCountStatesItemProvider yCountStatesItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YCountStates}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYCountStatesAdapter()
	{
		if (yCountStatesItemProvider == null) {
			yCountStatesItemProvider = new YCountStatesItemProvider(this);
		}

		return yCountStatesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YSetAbsoluteNodePropability} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YSetAbsoluteNodePropabilityItemProvider ySetAbsoluteNodePropabilityItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YSetAbsoluteNodePropability}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYSetAbsoluteNodePropabilityAdapter()
	{
		if (ySetAbsoluteNodePropabilityItemProvider == null) {
			ySetAbsoluteNodePropabilityItemProvider = new YSetAbsoluteNodePropabilityItemProvider(this);
		}

		return ySetAbsoluteNodePropabilityItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YCountReachableStates} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YCountReachableStatesItemProvider yCountReachableStatesItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YCountReachableStates}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYCountReachableStatesAdapter()
	{
		if (yCountReachableStatesItemProvider == null) {
			yCountReachableStatesItemProvider = new YCountReachableStatesItemProvider(this);
		}

		return yCountReachableStatesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YCountInValidTransitions} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YCountInValidTransitionsItemProvider yCountInValidTransitionsItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YCountInValidTransitions}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYCountInValidTransitionsAdapter()
	{
		if (yCountInValidTransitionsItemProvider == null) {
			yCountInValidTransitionsItemProvider = new YCountInValidTransitionsItemProvider(this);
		}

		return yCountInValidTransitionsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YSetPopulationSize} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YSetPopulationSizeItemProvider ySetPopulationSizeItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YSetPopulationSize}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYSetPopulationSizeAdapter()
	{
		if (ySetPopulationSizeItemProvider == null) {
			ySetPopulationSizeItemProvider = new YSetPopulationSizeItemProvider(this);
		}

		return ySetPopulationSizeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YLoadModel} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YLoadModelItemProvider yLoadModelItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YLoadModel}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYLoadModelAdapter()
	{
		if (yLoadModelItemProvider == null) {
			yLoadModelItemProvider = new YLoadModelItemProvider(this);
		}

		return yLoadModelItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.DslInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DslInfoItemProvider dslInfoItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.DslInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDslInfoAdapter()
	{
		if (dslInfoItemProvider == null) {
			dslInfoItemProvider = new DslInfoItemProvider(this);
		}

		return dslInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.FeatureInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FeatureInfoItemProvider featureInfoItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.FeatureInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFeatureInfoAdapter()
	{
		if (featureInfoItemProvider == null) {
			featureInfoItemProvider = new FeatureInfoItemProvider(this);
		}

		return featureInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.SingleLinePropertyInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SingleLinePropertyInfoItemProvider singleLinePropertyInfoItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.SingleLinePropertyInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSingleLinePropertyInfoAdapter()
	{
		if (singleLinePropertyInfoItemProvider == null) {
			singleLinePropertyInfoItemProvider = new SingleLinePropertyInfoItemProvider(this);
		}

		return singleLinePropertyInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.GuardInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GuardInfoItemProvider guardInfoItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.GuardInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGuardInfoAdapter()
	{
		if (guardInfoItemProvider == null) {
			guardInfoItemProvider = new GuardInfoItemProvider(this);
		}

		return guardInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.EffectInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EffectInfoItemProvider effectInfoItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.EffectInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEffectInfoAdapter()
	{
		if (effectInfoItemProvider == null) {
			effectInfoItemProvider = new EffectInfoItemProvider(this);
		}

		return effectInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.ContainmentInfo} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ContainmentInfoItemProvider containmentInfoItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.ContainmentInfo}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createContainmentInfoAdapter()
	{
		if (containmentInfoItemProvider == null) {
			containmentInfoItemProvider = new ContainmentInfoItemProvider(this);
		}

		return containmentInfoItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link java.util.Map.Entry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EStructuralFeatureToFeatureInfoMapItemProvider eStructuralFeatureToFeatureInfoMapItemProvider;

	/**
	 * This creates an adapter for a {@link java.util.Map.Entry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEStructuralFeatureToFeatureInfoMapAdapter()
	{
		if (eStructuralFeatureToFeatureInfoMapItemProvider == null) {
			eStructuralFeatureToFeatureInfoMapItemProvider = new EStructuralFeatureToFeatureInfoMapItemProvider(this);
		}

		return eStructuralFeatureToFeatureInfoMapItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.Line} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LineItemProvider lineItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.Line}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLineAdapter()
	{
		if (lineItemProvider == null) {
			lineItemProvider = new LineItemProvider(this);
		}

		return lineItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YStructure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YStructureItemProvider yStructureItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YStructure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYStructureAdapter()
	{
		if (yStructureItemProvider == null) {
			yStructureItemProvider = new YStructureItemProvider(this);
		}

		return yStructureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YInternal} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YInternalItemProvider yInternalItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YInternal}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYInternalAdapter() {
		if (yInternalItemProvider == null) {
			yInternalItemProvider = new YInternalItemProvider(this);
		}

		return yInternalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YTimeStep} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YTimeStepItemProvider yTimeStepItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YTimeStep}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYTimeStepAdapter() {
		if (yTimeStepItemProvider == null) {
			yTimeStepItemProvider = new YTimeStepItemProvider(this);
		}

		return yTimeStepItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link online.yamm.coreModelXmi.yamm.YObserverAddValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected YObserverAddValueItemProvider yObserverAddValueItemProvider;

	/**
	 * This creates an adapter for a {@link online.yamm.coreModelXmi.yamm.YObserverAddValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createYObserverAddValueAdapter() {
		if (yObserverAddValueItemProvider == null) {
			yObserverAddValueItemProvider = new YObserverAddValueItemProvider(this);
		}

		return yObserverAddValueItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory()
	{
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory)
	{
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type)
	{
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type)
	{
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type)
	{
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener)
	{
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener)
	{
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification)
	{
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose()
	{
		if (yClassItemProvider != null) yClassItemProvider.dispose();
		if (yClassifierItemProvider != null) yClassifierItemProvider.dispose();
		if (yCommentItemProvider != null) yCommentItemProvider.dispose();
		if (yConstraintItemProvider != null) yConstraintItemProvider.dispose();
		if (yDataTypeItemProvider != null) yDataTypeItemProvider.dispose();
		if (yElementItemProvider != null) yElementItemProvider.dispose();
		if (yElementImportItemProvider != null) yElementImportItemProvider.dispose();
		if (yEnumerationItemProvider != null) yEnumerationItemProvider.dispose();
		if (yEnumerationLiteralItemProvider != null) yEnumerationLiteralItemProvider.dispose();
		if (yFeatureItemProvider != null) yFeatureItemProvider.dispose();
		if (yNamedElementItemProvider != null) yNamedElementItemProvider.dispose();
		if (yNamespaceItemProvider != null) yNamespaceItemProvider.dispose();
		if (yOperationItemProvider != null) yOperationItemProvider.dispose();
		if (yPackageItemProvider != null) yPackageItemProvider.dispose();
		if (yPackageableElementItemProvider != null) yPackageableElementItemProvider.dispose();
		if (yPackageImportItemProvider != null) yPackageImportItemProvider.dispose();
		if (yParameterItemProvider != null) yParameterItemProvider.dispose();
		if (yPrimitiveTypeItemProvider != null) yPrimitiveTypeItemProvider.dispose();
		if (yPropertyItemProvider != null) yPropertyItemProvider.dispose();
		if (yTypeItemProvider != null) yTypeItemProvider.dispose();
		if (yStateMachineItemProvider != null) yStateMachineItemProvider.dispose();
		if (yTransitionItemProvider != null) yTransitionItemProvider.dispose();
		if (yTrAttachmentItemProvider != null) yTrAttachmentItemProvider.dispose();
		if (yEffectItemProvider != null) yEffectItemProvider.dispose();
		if (yVertexItemProvider != null) yVertexItemProvider.dispose();
		if (yPseudostateItemProvider != null) yPseudostateItemProvider.dispose();
		if (yFinalStateItemProvider != null) yFinalStateItemProvider.dispose();
		if (yStateItemProvider != null) yStateItemProvider.dispose();
		if (yModelItemProvider != null) yModelItemProvider.dispose();
		if (ySharedEdgeItemProvider != null) ySharedEdgeItemProvider.dispose();
		if (yCompositeEdgeItemProvider != null) yCompositeEdgeItemProvider.dispose();
		if (yObjectItemProvider != null) yObjectItemProvider.dispose();
		if (yStateMachineHandlerItemProvider != null) yStateMachineHandlerItemProvider.dispose();
		if (yGlobalStateMachineItemProvider != null) yGlobalStateMachineItemProvider.dispose();
		if (yCreateInstanceExpressionItemProvider != null) yCreateInstanceExpressionItemProvider.dispose();
		if (yPrintExpressionItemProvider != null) yPrintExpressionItemProvider.dispose();
		if (ySetReturnValueItemProvider != null) ySetReturnValueItemProvider.dispose();
		if (yGetInstancesOfExpressionItemProvider != null) yGetInstancesOfExpressionItemProvider.dispose();
		if (yMemberFeatureCallItemProvider != null) yMemberFeatureCallItemProvider.dispose();
		if (yFeatureCallItemProvider != null) yFeatureCallItemProvider.dispose();
		if (yGetObjectManagementItemProvider != null) yGetObjectManagementItemProvider.dispose();
		if (yGetLayerInformationItemProvider != null) yGetLayerInformationItemProvider.dispose();
		if (yColorDFAObjectItemProvider != null) yColorDFAObjectItemProvider.dispose();
		if (yGetInstancesItemProvider != null) yGetInstancesItemProvider.dispose();
		if (yCountFinalStatesItemProvider != null) yCountFinalStatesItemProvider.dispose();
		if (yCountInitialStatesItemProvider != null) yCountInitialStatesItemProvider.dispose();
		if (yCountStatesItemProvider != null) yCountStatesItemProvider.dispose();
		if (ySetAbsoluteNodePropabilityItemProvider != null) ySetAbsoluteNodePropabilityItemProvider.dispose();
		if (yCountReachableStatesItemProvider != null) yCountReachableStatesItemProvider.dispose();
		if (yCountInValidTransitionsItemProvider != null) yCountInValidTransitionsItemProvider.dispose();
		if (ySetPopulationSizeItemProvider != null) ySetPopulationSizeItemProvider.dispose();
		if (yLoadModelItemProvider != null) yLoadModelItemProvider.dispose();
		if (dslInfoItemProvider != null) dslInfoItemProvider.dispose();
		if (featureInfoItemProvider != null) featureInfoItemProvider.dispose();
		if (singleLinePropertyInfoItemProvider != null) singleLinePropertyInfoItemProvider.dispose();
		if (guardInfoItemProvider != null) guardInfoItemProvider.dispose();
		if (effectInfoItemProvider != null) effectInfoItemProvider.dispose();
		if (containmentInfoItemProvider != null) containmentInfoItemProvider.dispose();
		if (eStructuralFeatureToFeatureInfoMapItemProvider != null) eStructuralFeatureToFeatureInfoMapItemProvider.dispose();
		if (lineItemProvider != null) lineItemProvider.dispose();
		if (yStructureItemProvider != null) yStructureItemProvider.dispose();
		if (yInternalItemProvider != null) yInternalItemProvider.dispose();
		if (yTimeStepItemProvider != null) yTimeStepItemProvider.dispose();
		if (yObserverAddValueItemProvider != null) yObserverAddValueItemProvider.dispose();
	}

}
