<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dfa" nsURI="http://www.yamm.dev/example/Dfa" nsPrefix="dfa">
  <eClassifiers xsi:type="ecore:EClass" name="DFA" eSuperTypes="#//RObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="1"
        upperBound="-1" eType="#//DTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
        upperBound="-1" eType="#//DState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialState" lowerBound="1"
        eType="#//DInitialState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ObjectID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        unsettable="true" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DState" eSuperTypes="#//RObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stateName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dIn" upperBound="-1" eType="#//DTransition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dOut" upperBound="-1" eType="#//DTransition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DFinalState" eSuperTypes="#//DState"/>
  <eClassifiers xsi:type="ecore:EClass" name="DInitialState" eSuperTypes="#//DState"/>
  <eClassifiers xsi:type="ecore:EClass" name="DInitialFinalState" eSuperTypes="#//DFinalState #//DInitialState"/>
  <eClassifiers xsi:type="ecore:EClass" name="DTransition" eSuperTypes="#//RObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dTarget" lowerBound="1"
        eType="#//DState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dSource" lowerBound="1"
        eType="#//DState"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
