/*
 * generated by Xtext 2.14.0
 */
package dev.yamm.coreModelDsl.formatting2

import com.google.inject.Inject
import dev.yamm.coreModelDsl.services.XYammGrammarAccess
import dev.yamm.coreModelXmi.yamm.YClass
import dev.yamm.coreModelXmi.yamm.YCreateInstanceExpression
import org.eclipse.xtext.formatting2.IFormattableDocument
import org.eclipse.xtext.xbase.formatting2.XbaseFormatter

class XYammFormatter extends XbaseFormatter {
	
	@Inject extension XYammGrammarAccess

	def dispatch void format(YClass rClass, extension IFormattableDocument document) {
		
			for (_operation : rClass.ownedOperation) {
				for (_trAttach : _operation.stateMachine.trAttach) {
					_trAttach.append[setNewLines(1)]
					_trAttach.regionFor.keyword("yEffects").append[newLine]
					_trAttach.regionFor.keyword("yGuard").append[newLine]
					_trAttach.regionFor.keyword("yGuard").previousSemanticRegion.append[newLine]
					for (_effect : _trAttach.effects) {
						_effect.append[setNewLines(1)]
						_effect.regionFor.keyword("{").append[newLine]
						val open = _effect.regionFor.keyword("{")
					}
				}
			}
		
	}

	def dispatch void format(YCreateInstanceExpression createInstanceExpression,
		extension IFormattableDocument document) {
	}
	
}
