/*
 * generated by Xtext 2.23.0
 */
package online.yamm.coreModelDsl.ui.tests;

import com.google.inject.Injector;
import online.yamm.coreModelDsl.ui.internal.CoreModelDslActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class XYammUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CoreModelDslActivator.getInstance().getInjector("online.yamm.coreModelDsl.XYamm");
	}

}
