/*
 * generated by Xtext 2.14.0
 */
package dev.yamm.coreModelDsl.ide

import com.google.inject.Guice
import dev.yamm.coreModelDsl.XYammRuntimeModule
import dev.yamm.coreModelDsl.XYammStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class XYammIdeSetup extends XYammStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new XYammRuntimeModule, new XYammIdeModule))
	}
	
}
