/*
 * generated by Xtext 2.24.0.M1
 */
package online.yamm.util.evalGrammar.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractEvalScopeProvider extends XbaseBatchScopeProvider {
}
